import type { FomoEvent } from '@/types/event';

type DemoEvent = Pick<
  FomoEvent,
  | 'id'
  | 'title'
  | 'category'
  | 'format'
  | 'start_date'
  | 'start_time'
  | 'venue_name'
  | 'address'
  | 'latitude'
  | 'longitude'
  | 'short_description'
  | 'description'
  | 'free'
  | 'price_label'
  | 'budget_range'
> & {
  mood: string;
  whyGo: string;
};

const demoEvents: DemoEvent[] = [
  {
    id: -101,
    title: 'Frequenze sotto le torri',
    category: 'Festival musicale',
    format: 'Festival',
    start_date: '2026-09-19',
    start_time: '20:30',
    venue_name: 'DumBO',
    address: 'Via Camillo Casarini 19',
    latitude: 44.5064,
    longitude: 11.3275,
    short_description: 'Elettronica, visual e live set in uno spazio post-industriale.',
    description: 'Una notte dedicata alla nuova scena elettronica italiana: live modulari, visual immersivi e DJ set si alternano negli spazi industriali di DumBO fino a tarda notte.',
    free: false,
    price_label: 'Da 18 €',
    budget_range: '€€',
    mood: 'Energia alta',
    whyGo: 'Per una notte lunga tra bassi, luci e archeologia industriale.',
  },
  {
    id: -102,
    title: 'Cinema sui tetti',
    category: 'Cinema',
    format: 'Festival',
    start_date: '2026-09-22',
    start_time: '21:00',
    venue_name: 'Manifattura delle Arti',
    address: 'Via Azzo Gardino 65',
    latitude: 44.5021,
    longitude: 11.3347,
    short_description: 'Cortometraggi indipendenti e sonorizzazioni dal vivo.',
    description: 'Una selezione di cortometraggi indipendenti italiani ed europei proiettati all’aperto, accompagnati da sonorizzazioni originali eseguite dal vivo.',
    free: true,
    price_label: 'Gratuito',
    budget_range: 'Free',
    mood: 'Sorpresa',
    whyGo: 'Per scoprire cinema fuori formato in una delle zone creative della città.',
  },
  {
    id: -103,
    title: 'Giardini sonori',
    category: 'Festival musicale',
    format: 'Festival',
    start_date: '2026-09-26',
    start_time: '17:30',
    venue_name: 'Giardini Margherita',
    address: 'Viale Giovanni Gozzadini',
    latitude: 44.4818,
    longitude: 11.3557,
    short_description: 'Live acustici, piccoli palchi e picnic al tramonto.',
    description: 'Un pomeriggio di concerti acustici diffusi tra i prati dei Giardini Margherita, con area picnic, piccoli produttori locali e attività per tutte le età.',
    free: true,
    price_label: 'Gratuito',
    budget_range: 'Free',
    mood: 'Chill',
    whyGo: 'Per chi vuole musica all’aperto senza rinunciare a una serata rilassata.',
  },
  {
    id: -104,
    title: 'Visioni radicali',
    category: 'Arte e design',
    format: 'Festival',
    start_date: '2026-10-02',
    start_time: '18:00',
    venue_name: 'MAMbo',
    address: 'Via Don Giovanni Minzoni 14',
    latitude: 44.5028,
    longitude: 11.3361,
    short_description: 'Installazioni, performance e incontri con giovani artisti.',
    description: 'Installazioni site-specific, performance e incontri esplorano il rapporto tra corpo, tecnologia e spazio pubblico attraverso il lavoro di artisti emergenti.',
    free: false,
    price_label: '12 €',
    budget_range: '€',
    mood: 'Ispirazione',
    whyGo: 'Per attraversare linguaggi nuovi in una sola serata.',
  },
  {
    id: -105,
    title: 'Parole in piazza',
    category: 'Talk e cultura',
    format: 'Festival',
    start_date: '2026-10-08',
    start_time: '19:00',
    venue_name: 'Piazza Santo Stefano',
    address: 'Piazza Santo Stefano',
    latitude: 44.4917,
    longitude: 11.3511,
    short_description: 'Autrici, podcast live e conversazioni sulla città che cambia.',
    description: 'Una serata di conversazioni dal vivo con scrittrici, autori e podcaster per raccontare identità urbane, nuovi linguaggi e trasformazioni sociali.',
    free: true,
    price_label: 'Gratuito',
    budget_range: 'Free',
    mood: 'Curiosità',
    whyGo: 'Per ascoltare idee contemporanee nel cuore medievale di Bologna.',
  },
  {
    id: -106,
    title: 'Officina notturna',
    category: 'Festival musicale',
    format: 'Festival',
    start_date: '2026-10-17',
    start_time: '22:00',
    venue_name: 'TPO',
    address: 'Via Camillo Casarini 17/5',
    latitude: 44.5056,
    longitude: 11.3269,
    short_description: 'Club culture, collettivi indipendenti e sperimentazione fino a tardi.',
    description: 'Collettivi indipendenti e producer internazionali condividono la consolle in una maratona sonora tra techno, bass music e sperimentazione audiovisiva.',
    free: false,
    price_label: '15 €',
    budget_range: '€€',
    mood: 'Notte fonda',
    whyGo: 'Per una selezione senza compromessi tra clubbing e ricerca sonora.',
  },
  {
    id: -107,
    title: 'Montagnola open air',
    category: 'Festival musicale',
    format: 'Rassegna open air',
    start_date: '2026-09-24',
    start_time: '18:30',
    venue_name: 'Parco della Montagnola',
    address: 'Via Irnerio 2/3',
    latitude: 44.5037,
    longitude: 11.3459,
    short_description: 'DJ set, street food e piccoli live nel verde del centro.',
    description: 'Il parco si trasforma in un piccolo villaggio musicale con DJ set, concerti al tramonto, cucine di strada e una selezione di progetti creativi locali.',
    free: true,
    price_label: 'Gratuito',
    budget_range: 'Free',
    mood: 'Aperitivo lungo',
    whyGo: 'Per iniziare presto e restare finché la musica continua.',
  },
  {
    id: -108,
    title: 'Suoni dal mercato',
    category: 'Musica live',
    format: 'Concerto',
    start_date: '2026-09-30',
    start_time: '21:15',
    venue_name: 'Mercato Sonato',
    address: 'Via Giuseppe Tartini 3',
    latitude: 44.5077,
    longitude: 11.3667,
    short_description: 'Jazz contemporaneo e contaminazioni mediterranee.',
    description: 'Un ensemble aperto intreccia jazz contemporaneo, ritmi nordafricani e improvvisazione, seguito da una jam session aperta ai musicisti presenti.',
    free: false,
    price_label: '10 €',
    budget_range: '€',
    mood: 'Groove',
    whyGo: 'Per ascoltare musicisti curiosi in uno spazio informale e accogliente.',
  },
  {
    id: -109,
    title: 'Serra elettronica',
    category: 'Arte e design',
    format: 'Performance',
    start_date: '2026-10-05',
    start_time: '19:30',
    venue_name: 'Le Serre dei Giardini Margherita',
    address: 'Via Castiglione 134',
    latitude: 44.4846,
    longitude: 11.3592,
    short_description: 'Sound art, botanica e proiezioni immersive tra le serre.',
    description: 'Musica ambient, field recording e proiezioni botaniche ridisegnano le serre per un percorso immersivo da attraversare liberamente al calare della sera.',
    free: false,
    price_label: '8 €',
    budget_range: '€',
    mood: 'Immersione',
    whyGo: 'Per vivere un incrocio insolito tra natura, luce e suono.',
  },
  {
    id: -110,
    title: 'Nuove scene',
    category: 'Teatro',
    format: 'Spettacolo',
    start_date: '2026-10-11',
    start_time: '20:45',
    venue_name: 'Teatro Duse',
    address: 'Via Cartoleria 42',
    latitude: 44.4877,
    longitude: 11.3519,
    short_description: 'Teatro fisico, narrazione e una scena trasformata dal pubblico.',
    description: 'Una creazione di teatro fisico porta in scena cinque performer e coinvolge il pubblico in un racconto corale sul modo in cui abitiamo le città.',
    free: false,
    price_label: 'Da 16 €',
    budget_range: '€€',
    mood: 'Intensità',
    whyGo: 'Per una serata teatrale contemporanea, fisica e imprevedibile.',
  },
  {
    id: -111,
    title: 'Pedala e racconta',
    category: 'Talk e cultura',
    format: 'Community event',
    start_date: '2026-10-15',
    start_time: '18:45',
    venue_name: 'Dynamo Velostazione',
    address: 'Via dell’Indipendenza 71/Z',
    latitude: 44.5021,
    longitude: 11.3431,
    short_description: 'Storie urbane, mobilità e musica in formato community night.',
    description: 'Cicliste, urbaniste e associazioni si incontrano per condividere storie di mobilità quotidiana, idee per la città e itinerari insoliti su due ruote.',
    free: true,
    price_label: 'Gratuito',
    budget_range: 'Free',
    mood: 'Community',
    whyGo: 'Per incontrare persone e idee che attraversano Bologna ogni giorno.',
  },
];

export const BOLOGNA_DEMO_EVENTS: FomoEvent[] = demoEvents.map(
  (event, index) => ({
    id: event.id,
    title: event.title,
    description: event.description,
    short_description: event.short_description,
    category: event.category,
    format: event.format,
    status: 'published',
    start_date: event.start_date,
    end_date: event.start_date,
    start_time: event.start_time,
    end_time: null,
    venue_name: event.venue_name,
    address: event.address,
    city: 'Bologna',
    region: 'Emilia-Romagna',
    latitude: event.latitude,
    longitude: event.longitude,
    price_min: null,
    price_max: null,
    free: event.free,
    official_url: null,
    booking_url: null,
    image_url: null,
    source_url: null,
    event_editorial: {
      why_go: event.whyGo,
      radar_note: 'Selezionato dalla redazione FOMO Radar Bologna.',
      best_for: null,
      not_for: null,
      hype_score: null,
      uniqueness_score: null,
      accessibility_score: null,
      price_score: null,
      radar_score: null,
    },
    event_moods: [
      {
        weight: 1,
        moods: {
          id: -201 - index,
          name: event.mood,
          slug: event.mood.toLowerCase().replace(/\s+/g, '-'),
        },
      },
    ],
    event_tags: [],
    duration_days: 1,
    month_label: event.start_date?.slice(0, 7) ?? null,
    curation_status: 'curated',
    budget_range: event.budget_range,
    price_label: event.price_label,
    lineup: null,
    instagram_handle: null,
    image_alt: null,
    image_credit: null,
    event_artists: [],
  })
);
